### ISSUE TITLE
Ensure_Image_Proportions pre_/post_process issues

### ISSUE THREAD

**Issue by guatavita** [brianmanderson/Image_Processors_Module#5]
Unwanted behavior, line 829, pre_process, np.resize() resize does not pad the image but duplicate its content.

Crashing behavior, line 846, post_process forgot a [None, ...] so the stacked dimension is the row dimension making the rest of the code fail. 

pred = [np.resize(i, new_shape=(self.pre_pad_rows, self.pre_pad_cols, pred.shape[-1]))[None, ...] for i in pred]

**Comment by guatavita** [comment]
Also, 

I think in post_process this line should be replace by (line 850):

From: pred = [image_resize(i, self.og_rows, self.og_cols, inter=cv2.INTER_LINEAR)[None, ...] for i in pred]
To: pred = [cv2.resize(i, (self.og_cols, self.og_rows), interpolation=cv2.INTER_LINEAR)[None, ...] for i in pred]

I had issue with this function for a weird CT scan. Image_resize was not recovering the image size but decreasing it even more. I may change it with some stuff I have from other processors. Currently just a quick fix.

**Comment by brianmanderson** [comment]
I've changed the behavior to first resize to the minimum dimension (maintaining aspect ratio of image) and then to pad with the minimum value to the desired size

Re-wrote the post-processing step to do the opposite. First trim back to original dimensions, then resize

commit b5673ed
